
services:
  web:
    build: .
    command: >
      /bin/sh -c "while ! mysqladmin ping -h db --silent; do sleep 1; done; python manage.py migrate"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - config.env
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      - config.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: