
services:
  web:
    build: .
    command: >
      sh -c "./wait-for-it.sh db:3306 -- sleep 10 && python manage.py migrate && gunicorn monitoring.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=monitoring.settings
    env_file: .env
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network



volumes:
  mysql_data:
networks:
  my_network: